apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  chart:
    repository: https://charts.konghq.com
    name: kong
    version: 1.15.0
  values:
    image:
      repository: kong-docker-kong-gateway-docker.bintray.io/kong-enterprise-edition
      tag: "2.3.2.0-alpine"

    env:
      prefix: /kong_prefix/
      database: postgres
      password:
        valueFrom:
          secretKeyRef:
            name: kong-enterprise-superuser-password #CHANGEME
            key: password #CHANGEME
      admin_api_uri: "https://<MINIKUBE-IP>:32444"
      admin_gui_url: "https://<MINIKUBE-IP>:32445"
      portal_api-url: "https://<MINIKUBE-IP>:32447"
      portal_gui_host: "<MINIKUBE-IP>:32446"
      portal_gui_protocol: "https"

    ingressController:
      enabled: false
      installCRDs: false

    admin:
      enabled: true
      tls:
        nodePort: 32444

    manager:
      enabled: true
      tls:
        nodePort: 32445

    portal:
      enabled: true
      tls:
        nodePort: 32446

    portalapi:
      enabled: true
      tls:
        nodePort: 32447

    postgresql:
      enabled: true
      postgresqlUsername: kong
      postgresqlDatabase: kong
      service:
        port: 5432

    enterprise:
      enabled: true
      license_secret: kong-enterprise-license
      portal:
        enabled: true
      rbac:
        enabled: true
        admin_gui_auth: basic-auth
        # If RBAC is enabled, this Secret must contain an admin_gui_session_conf key
        # The key value must be a secret configuration, following the example at
        # https://docs.konghq.com/enterprise/latest/kong-manager/authentication/sessions
        session_conf_secret: kong-session-config
