apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  chart:
    repository: https://charts.konghq.com
    name: kong
    version: 1.15.0
  values:
    image:
      repository: kong-docker-kong-gateway-docker.bintray.io/kong-enterprise-edition
      tag: "2.3.2.0-alpine"

    env:
      prefix: /kong_prefix/
      database: postgres
      pg_host: kong-dev-instance-1.cxctrb8czfb4.us-east-1.rds.amazonaws.com
      pg_port: '5432'
      pg_database:
        valueFrom:
          secretKeyRef:
            name: kong-postgres-dev
            key: pg_database
      pg_user:
        valueFrom:
          secretKeyRef:
            name: kong-postgres-dev
            key: pg_user
      pg_password:
        valueFrom:
          secretKeyRef:
            name: kong-postgres-dev
            key: pg_password

    ingressController:
      enabled: false
      installCRDs: false

    enterprise:
      enabled: true
      license_secret: kong-enterprise-license

    portal:
      enabled: false

    portalapi:
      enabled: false

    manager:
      enabled: false

    proxy:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: owner=APIP,environment=kube
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '300'
        service.beta.kubernetes.io/aws-load-balancer-internal: 10.0.0.0/8
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:528214016699:certificate/5f70dc84-c827-4899-80b2-2fe38cb459a1
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
