apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  chart:
    repository: https://charts.konghq.com
    name: kong
    version: 1.15.0
  values:
    image:
      repository: kong-docker-kong-gateway-docker.bintray.io/kong-enterprise-edition
      tag: "2.3.2.0-alpine"

    env:
      prefix: /kong_prefix/
      database: postgres
      password:
        valueFrom:
          secretKeyRef:
            name: kong-enterprise-superuser-password #CHANGEME
            key: password #CHANGEME
      admin_api_uri: "https://192.168.64.38:30712"
      admin_gui_url: "https://192.168.64.38:32130"
      portal_api-url: "https://192.168.64.38:31736"
      portal_gui_host: "192.168.64.38:32610"
      portal_gui_protocol: "https"
      # pg_host: kong-dev-instance-1.cxctrb8czfb4.us-east-1.rds.amazonaws.com
      # pg_port: '5432'
      # pg_database:
      #   valueFrom:
      #     secretKeyRef:
      #       name: kong-postgres-dev
      #       key: pg_database
      # pg_user:
      #   valueFrom:
      #     secretKeyRef:
      #       name: kong-postgres-dev
      #       key: pg_user
      # pg_password:
      #   valueFrom:
      #     secretKeyRef:
      #       name: kong-postgres-dev
      #       key: pg_password

    ingressController:
      enabled: false
      installCRDs: false

    admin:
      enabled: true

    portal:
      enabled: true

    postgresql:
      enabled: true
      postgresqlUsername: kong
      postgresqlDatabase: kong
      service:
        port: 5432

    enterprise:
      enabled: true
      license_secret: kong-enterprise-license
      portal:
        enabled: true
      rbac:
        enabled: true
        admin_gui_auth: basic-auth
        # If RBAC is enabled, this Secret must contain an admin_gui_session_conf key
        # The key value must be a secret configuration, following the example at
        # https://docs.konghq.com/enterprise/latest/kong-manager/authentication/sessions
        session_conf_secret: kong-session-config
